# Generated by Django 5.2.8 on 2025-11-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
