# Generated by Django 5.2.8 on 2025-11-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_rename_result_classification_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='description',
        ),
        migrations.AddField(
            model_name='classification',
            name='cracked_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classification',
            name='uncracked_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
